/* eslint-disable camelcase */
/*
 * Copyright 2017 ClinRisk Ltd.
 *
 * This file is part of QDiabetes-2018 (https://qdiabetes.org).
 *
 * QDiabetes-2018 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * QDiabetes-2018 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with QDiabetes-2018.  If not, see http://www.gnu.org/licenses/.
 *
 * Additional terms
 *
 * The following disclaimer must be held together with any risk score score generated by this code.
 * If the score is displayed, then this disclaimer must be displayed or otherwise be made easily accessible, e.g. by a prominent link alongside it.
 *   The initial version of this file, to be found at http://qdiabetes.org, faithfully implements QDiabetes-2018.
 *   ClinRisk Ltd. have released this code under the GNU Affero General Public License to enable others to implement the algorithm faithfully.
 *   However, the nature of the GNU Affero General Public License is such that we cannot prevent, for example, someone accidentally
 *   altering the coefficients, getting the inputs wrong, or just poor programming.
 *   ClinRisk Ltd. stress, therefore, that it is the responsibility of the end user to check that the source that they receive produces the same
 *   results as the original code found at http://qdiabetes.org.
 *   Inaccurate implementations of risk scores can lead to wrong patients being given the wrong treatment.
 *
 * End of additional terms
 *
 */

// Model B

export default function (
  age, b_atypicalantipsy, b_corticosteroids, b_cvd, b_learning, b_manicschiz, b_statin, b_treatedhyp, bmi, ethrisk, fbs, fh_diab, smoke_cat, surv, town
) {
  surv = 10
  const survivor = [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.985019445419312
  ]

  /* The conditional arrays */

  const Iethrisk = [
    0,
    0,
    1.0081475800686235000000000,
    1.3359138425778705000000000,
    1.4815419524892652000000000,
    1.0384996851820663000000000,
    0.5202348070887524700000000,
    0.8579673418258558800000000,
    0.6413108960765615500000000,
    0.4838340220821504800000000
  ]
  const Ismoke = [
    0,
    0.1119475792364162500000000,
    0.3110132095412204700000000,
    0.3328898469326042100000000,
    0.4257069026941993100000000
  ]

  /* Applying the fractional polynomial transforms */
  /* (which includes scaling)                      */

  let dage = age
  dage = dage / 10
  let age_1 = Math.log(dage)
  let age_2 = dage ** 3
  let dbmi = bmi
  dbmi = dbmi / 10
  let bmi_1 = dbmi ** 2
  let bmi_2 = dbmi ** 3
  const dfbs = fbs

  let fbs_1 = dfbs ** -0.5
  let fbs_2 = dfbs ** -0.5 * Math.log(dfbs)

  /* Centring the continuous variables */

  age_1 = age_1 - 1.496392488479614
  age_2 = age_2 - 89.048171997070313
  bmi_1 = bmi_1 - 6.817805767059326
  bmi_2 = bmi_2 - 17.801923751831055
  fbs_1 = fbs_1 - 0.448028832674026
  fbs_2 = fbs_2 - 0.719442605972290
  town = town - 0.515986680984497

  /* Start of Sum */
  let a = 0

  /* The conditional sums */

  a += Iethrisk[ethrisk]
  a += Ismoke[smoke_cat]

  /* Sum from continuous values */

  a += age_1 * 4.1149143302364717000000000
  a += age_2 * -0.0047593576668505362000000
  a += bmi_1 * 0.8169361587644297100000000
  a += bmi_2 * -0.1250237740343336200000000
  a += fbs_1 * -54.8417881280971070000000000
  a += fbs_2 * -53.1120784984813600000000000
  a += town * 0.0253741755198943560000000

  /* Sum from boolean values */

  a += b_atypicalantipsy * 0.4417934088889577400000000
  a += b_corticosteroids * 0.3413547348339454100000000
  a += b_cvd * 0.2158977454372756600000000
  a += b_learning * 0.4012885027585300100000000
  a += b_manicschiz * 0.2181769391399779300000000
  a += b_statin * 0.5147657600111734700000000
  a += b_treatedhyp * 0.2467209287407037300000000
  a += fh_diab * 0.5749437333987512700000000

  /* Sum from interaction terms */

  a += age_1 * b_atypicalantipsy * -0.9502224313823126600000000
  a += age_1 * b_learning * -0.8358370163090045300000000
  a += age_1 * b_statin * -1.8141786919269460000000000
  a += age_1 * bmi_1 * 0.3748482092078384600000000
  a += age_1 * bmi_2 * -0.0909836579562487420000000
  a += age_1 * fbs_1 * 21.0117301217643340000000000
  a += age_1 * fbs_2 * 23.8244600447469740000000000
  a += age_1 * fh_diab * -0.6780647705291665800000000
  a += age_2 * b_atypicalantipsy * 0.0001472972077162874300000
  a += age_2 * b_learning * 0.0006012919264966409100000
  a += age_2 * b_statin * 0.0016393484911405418000000
  a += age_2 * bmi_1 * -0.0010774782221531713000000
  a += age_2 * bmi_2 * 0.0001911048730458310100000
  a += age_2 * fbs_1 * -0.0390046079223835270000000
  a += age_2 * fbs_2 * -0.0411277198058959470000000
  a += age_2 * fh_diab * 0.0006257588248859499300000

  /* Calculate the score itself */
  const score = 100.0 * (1 - (survivor[surv]) ** Math.exp(a))
  return score
}
